import { MailerSend, EmailParams, Sender, Recipient } from "mailersend";
import { NextResponse } from "next/server";

const mailersend = new MailerSend({
    apiKey: process.env.MAILERSEND_TOKEN || "",
});

export async function POST(request: Request) {
    try {
        const { firstName, lastName, telephone, email } = await request.json();

        if (!firstName || !lastName || !telephone || !email) {
            return NextResponse.json(
                { error: "Missing required fields" },
                { status: 400 }
            );
        }

        const sentFrom = new Sender(
            process.env.MAILERSEND_FROM || "no-reply@gaptransportation.org",
            "GAP Web Portal"
        );

        const recipients = [
            new Recipient(process.env.MAILERSEND_ADMIN_TO || "gaptrasnport@gmail.com", "GAP Admin"),
        ];

        const html = `
      <!DOCTYPE html>
      <html>
        <head>
          <style>
            body { font-family: 'Arial', sans-serif; line-height: 1.6; color: #333; }
            .container { max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 10px; }
            .header { background-color: #1e3a8a; color: #ffffff; padding: 20px; text-align: center; border-radius: 10px 10px 0 0; }
            .content { padding: 30px; }
            .info-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            .info-table th { text-align: left; padding: 10px; border-bottom: 1px solid #f0f0f0; color: #1e3a8a; }
            .info-table td { padding: 10px; border-bottom: 1px solid #f0f0f0; }
            .footer { text-align: center; padding: 20px; font-size: 0.8em; color: #777; }
            .highlight { color: #facc15; font-weight: bold; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>GAP Transportation</h1>
              <p>New Careers Application</p>
            </div>
            <div class="content">
              <p>Hello Admin,</p>
              <p>You have received a new application interest from the GAP Transportation website. Here are the details of the interested candidate:</p>
              
              <table class="info-table">
                <tr>
                  <th>First Name</th>
                  <td>${firstName}</td>
                </tr>
                <tr>
                  <th>Last Name</th>
                  <td>${lastName}</td>
                </tr>
                <tr>
                  <th>Telephone</th>
                  <td>${telephone}</td>
                </tr>
                <tr>
                  <th>Email</th>
                  <td>${email}</td>
                </tr>
              </table>
              
              <p style="margin-top: 30px;">Please contact the candidate at your earliest convenience.</p>
            </div>
            <div class="footer">
              <p>This email was automatically generated by the GAP Transportation Web Portal.</p>
            </div>
          </div>
        </body>
      </html>
    `;

        const emailParams = new EmailParams()
            .setFrom(sentFrom)
            .setTo(recipients)
            .setReplyTo(sentFrom)
            .setSubject(`[GAP Careers] New Interested Applicant: ${firstName} ${lastName}`)
            .setHtml(html)
            .setText(`New Applicant: ${firstName} ${lastName}\nTelephone: ${telephone}\nEmail: ${email}`);

        await mailersend.email.send(emailParams);

        return NextResponse.json({ success: true, message: "Email sent successfully" });
    } catch (error: any) {
        console.error("MailerSend Error:", error);
        return NextResponse.json(
            { error: "Failed to send email", details: error.message },
            { status: 500 }
        );
    }
}
